server:
  port: 8081

spring:
  application:
    name: project-builder

  datasource:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10
    url: jdbc:h2:~/test
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
